### ISSUE TITLE
Unused code in MessageWebView: postMessage

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [acsant/react-native-recaptcha#14]
Hi, thanks for making this package! I'm copying it locally for development testing (#10 is getting in the way) and noticed that `MessageWebView`'s `postMessage` refers to `this.WebView` and doesn't seem to be used by anything. Should that code be deleted?

**Comment by BajajSaajan** [comment]
@JoshuaKGoldberg are you able to get the token? Kindly assist, if you are able to get the token.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues I no longer have context on. If anybody else is still seeing this, I'd encourage you to file a new issue with more information. Cheers!
